#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "[i] Performing ESLint fixes..."
npx eslint -c backend/.eslintrc.json --fix --cache backend/src
npx eslint -c frontend/.eslintrc.json --fix --cache frontend/src
