name: Build and Publish

on:
    push:
        branches:
            - 'master'
        tags:
            - v*
    pull_request:

jobs:
    build-and-push:
        name: Build Docker image and push to Docker Hub
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Read version
              id: version
              uses: juliangruber/read-file-action@v1
              with:
                  path: ./.version

            - name: Build image and push to Docker Hub
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: .
                  # Note: tags has to be all lower-case
                  tags: |
                      chlod/pagasa-parser-web:latest 
                      chlod/pagasa-parser-web:${{ steps.version.outputs.content }}
                  # Only push when tagged
                  push: ${{ github.ref_type == 'tag' }}

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
